version: '3.8'

services:
  app:
    build:
     context: .
     dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./query/query_txt
        target: /app/query/query_txt
      - type: bind
        source: ./query/query_data
        target: /app/query/query_data
      - type: bind
        source: ../db_data
        target: /app/db_data
    env_file:
      - .env
    ports:
      - "8000:8000"